%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(retem_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.

remove_leading_brace(Chars, Len) -> lists:sublist(Chars, 2, Len - 1).

string_to_float([$-|Chars]) -> -list_to_float(Chars);
string_to_float(Chars) -> list_to_float(Chars).
  
string_to_integer([$-|Chars]) -> -list_to_integer(Chars);
string_to_integer(Chars) -> list_to_integer(Chars).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%%    {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%%  Note the line number going into yystate, L0, is line of token
%%  start while line number returned is line of token end. We want line
%%  of token start.

string([], L, [], Ts) ->			%No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
	{A,Alen,Ics1,L1} ->			%Accepting end state
	    string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
	{A,Alen,Ics1,L1,_S1} ->			%Accepting transistion state
	    string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
	{reject,_Alen,Tlen,_Ics1,L1,_S1} ->	%After a non-accepting state
	    {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
	{A,Alen,_Tlen,_Ics1,L1,_S1} ->
	    string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%%  Test for and remove the end token wrapper. Push back characters
%%  are prepended to RestChars.

string_cont(Rest, Line, [{token, H}|T], Ts) ->
	string_cont(Rest, Line, T, [H|Ts]);
string_cont(Rest, Line, [], Ts) ->
	string(Rest, Line, Rest, Ts);

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%%    {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%%       AcceptAction, AcceptLen) ->
%%    {more,Continuation} | {done,ReturnVal,RestChars}.
%%  The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
	%% Accepting end state, we have a token.
	{A1,Alen1,Ics1,L1} ->
	    token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
	%% Accepting transition state, can take more chars.
	{A1,Alen1,[],L1,S1} ->			%Need more chars to check
	    {more,{token,S1,Tcs,L1,Alen1,Tline,A1,Alen1}};
	{A1,Alen1,Ics1,L1,_S1} ->		%Take what we got
	    token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
	%% After a non-accepting state, maybe reach accept state later.
	{A1,Alen1,Tlen1,[],L1,S1} ->		%Need more chars to check
	    {more,{token,S1,Tcs,L1,Tlen1,Tline,A1,Alen1}};
	{reject,_Alen1,Tlen1,eof,L1,_S1} ->	%No token match
	    %% Check for partial token which is error.
	    Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
					  %% Skip eof tail in Tcs.
					  {illegal,yypre(Tcs, Tlen1)}},L1};
		     true -> {eof,L1}
		  end,
	    {done,Ret,eof};
	{reject,_Alen1,Tlen1,Ics1,L1,_S1} ->	%No token match
	    Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
	    {done,{error,Error,L1},Ics1};
	{A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->	%Use last accept match
	    token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% tokens_cont(RestChars, Line, Token)
%%  If we have a token or error then return done, else if we have a
%%  skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%%    {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%%        AcceptAction, AcceptLen) ->
%%    {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
	%% Accepting end state, we have a token.
	{A1,Alen1,Ics1,L1} ->
	    tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
	%% Accepting transition state, can take more chars.
	{A1,Alen1,[],L1,S1} ->			%Need more chars to check
	    {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
	{A1,Alen1,Ics1,L1,_S1} ->		%Take what we got
	    tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
	%% After a non-accepting state, maybe reach accept state later.
	{A1,Alen1,Tlen1,[],L1,S1} ->		%Need more chars to check
	    {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
	{reject,_Alen1,Tlen1,eof,L1,_S1} ->	%No token match
	    %% Check for partial token which is error, no need to skip here.
	    Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
					  %% Skip eof tail in Tcs.
					  {illegal,yypre(Tcs, Tlen1)}},L1};
		     Ts == [] -> {eof,L1};
		     true -> {ok,yyrev(Ts),L1}
		  end,
	    {done,Ret,eof};
	{reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
	    %% Skip rest of tokens.
	    Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
	    skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
	{A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
	    Token = yyaction(A1, Alen1, Tcs, Tline),
	    tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%%  If we have a end_token or error then return done, else if we have
%%  a token then save it and continue, else if we have a skip_token
%%  just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%%  Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error)                           ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%%             AcceptAction, AcceptLen) ->
%%    {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
	{A1,Alen1,Ics1,L1} ->			%Accepting end state
	    skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
	{A1,Alen1,[],L1,S1} ->			%After an accepting state
	    {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
	{A1,Alen1,Ics1,L1,_S1} ->
	    skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
	{A1,Alen1,Tlen1,[],L1,S1} ->		%After a non-accepting state
	    {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
	{reject,_Alen1,_Tlen1,eof,L1,_S1} ->
	    {done,{error,Error,L1},eof};
	{reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
	    skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
	{A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
	    Token = yyaction(A1, Alen1, Tcs, Tline),
	    skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%%  Skip tokens until we have an end_token or error then return done
%%  with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%%      {Action, AcceptLen, RestChars, Line} |
%%      {Action, AcceptLen, RestChars, Line, State} |
%%      {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%%      {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

yystate() -> 23.

yystate(54, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,54};
yystate(53, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [$e|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [$i|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [$o|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $f, C =< $h ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $j, C =< $n ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= $p, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(51, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$l|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$m|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$n|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$o|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$p|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [$q|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $k ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= $r, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,51};
yystate(50, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,50};
yystate(49, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [$e|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= $f, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,49};
yystate(48, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, [$e|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= $f, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,48};
yystate(47, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [$t|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $s ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= $u, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,47};
yystate(46, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 15, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 15, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 15, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 15, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(44, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, [$i|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $h ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= $j, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,44};
yystate(43, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [$r|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $q ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= $s, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,43};
yystate(42, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,42};
yystate(41, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [$d|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $c ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= $e, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(39, [$\n|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line+1, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= $\000, C =< $\t ->
    yystate(39, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= $\v, C =< $z ->
    yystate(39, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= $|, C =< $ÿ ->
    yystate(39, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(37, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,37};
yystate(36, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [$n|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $m ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= $o, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,36};
yystate(35, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,35};
yystate(34, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [$t|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $s ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= $u, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,34};
yystate(33, [$.|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 19, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(33, Ics, Line, Tlen+1, 19, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,33};
yystate(32, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [$f|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [$n|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $e ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= $g, C =< $m ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= $o, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,32};
yystate(31, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, [$e|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= $f, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,31};
yystate(30, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [$s|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $r ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= $t, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,30};
yystate(29, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [$s|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $r ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= $t, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,29};
yystate(28, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [$l|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $k ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= $m, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,28};
yystate(27, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 6, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 6, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 6, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 6, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,27};
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(26, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,26};
yystate(25, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [$q|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [$r|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [$s|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $p ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= $t, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(23, [$\n|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line+1, Tlen+1, Action, Alen);
yystate(23, [$*|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$+|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$,|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$-|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$.|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$/|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$a|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$e|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$f|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$g|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$h|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$i|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$j|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$k|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$l|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$m|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$n|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$o|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$t|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$u|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [${|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [$}|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $\000, C =< $\t ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $\v, C =< $\s ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $0, C =< $9 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $A, C =< $Z ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $b, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $p, C =< $s ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= $v, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,22};
yystate(21, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [$a|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [$o|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= $b, C =< $n ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= $p, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,21};
yystate(20, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [$u|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $t ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= $v, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,20};
yystate(19, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [$s|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $r ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= $t, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,19};
yystate(18, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 11, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,18};
yystate(17, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, [$l|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $k ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= $m, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,17};
yystate(16, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [$r|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $q ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= $s, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,16};
yystate(15, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 14, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 14, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 14, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 14, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,15};
yystate(14, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [$n|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $m ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= $o, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,14};
yystate(13, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(12, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [$e|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [$i|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $d ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= $f, C =< $h ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= $j, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,12};
yystate(11, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [$r|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $q ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= $s, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,11};
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,10};
yystate(9, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [$f|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $e ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= $g, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,9};
yystate(8, [$\n|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= $\000, C =< $\t ->
    yystate(8, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= $\v, C =< $\s ->
    yystate(8, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,8};
yystate(7, [$\n|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= $\000, C =< $\t ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= $\v, C =< $z ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= $|, C =< $ÿ ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,7};
yystate(6, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,6};
yystate(5, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [$s|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $r ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= $t, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,5};
yystate(4, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [$d|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $c ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= $e, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,4};
yystate(3, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [$t|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $s ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= $u, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,3};
yystate(2, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [$l|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $k ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= $m, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,2};
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= $0, C =< $9 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [$_|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, [$q|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= $0, C =< $9 ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= $A, C =< $Z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= $a, C =< $p ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= $r, C =< $z ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%%        {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    {token,{'{'}};
yyaction(1, _, _, _) ->
    {token,{'}'}};
yyaction(2, _, _, _) ->
    {token,{'/'}};
yyaction(3, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    [{token,{'}'}},
     {token,{text,remove_leading_brace(TokenChars, TokenLen)}}];
yyaction(4, _, _, _) ->
    {token,{comma}};
yyaction(5, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{reserved,list_to_atom(TokenChars)}};
yyaction(6, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{op,logical,list_to_atom(TokenChars)}};
yyaction(7, _, _, _) ->
    {token,{nt}};
yyaction(8, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{op,comparator,list_to_atom(TokenChars)}};
yyaction(9, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{op,arithmetic,list_to_atom(TokenChars)}};
yyaction(10, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{conditional,list_to_atom(TokenChars)}};
yyaction(11, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{conditional_else,list_to_atom(TokenChars)}};
yyaction(12, _, _, _) ->
    {token,{nest}};
yyaction(13, _, _, _) ->
    {token,{endc}};
yyaction(14, _, _, _) ->
    {token,{for}};
yyaction(15, _, _, _) ->
    {token,{in}};
yyaction(16, _, _, _) ->
    {token,{dot}};
yyaction(17, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{identifier,list_to_atom(TokenChars)}};
yyaction(18, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{value,string_to_float(TokenChars)}};
yyaction(19, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    {token,{value,string_to_integer(TokenChars)}};
yyaction(20, _, _, _) ->
    skip_token;
yyaction(_, _, _, _) -> error.
